### ISSUE TITLE
Работа со строками

### ISSUE THREAD

**Issue by egpro** [valyavidyaeva/py-course--dz3#2]
https://github.com/valyavidyaeva/py-course--dz3/blob/ce092f47fb8767fcf41993b4e14cd6bd57b9513d/dz3-files.py#L41

Когда нужно объединить несколько строк в одну, лучше не использовать оператор "+". А воспользоваться одной из следующих конструкций:
1) Либо использовать внутреннюю функцию строк .join
2) Либо использовать format

**Comment by valyavidyaeva** [comment]
@egpro , исправила на метод .join и подкорректировала табуляцию
